### ISSUE TITLE
Disc title & time, but no tracks (from CD or optical)

### ISSUE THREAD

**Issue by astnmrtn** [gavinbenda/platinum-md#14]
Firstly, I love this app. Thanks so much for making it!

The issues below are only for MDs recorded from CD or optical sources.

Only one of my tested MDs, a 2019 release SACD with track names, shows up fully on the track listing. Other MDs, recorded from either older CD (no track names) or from optical input, do not show. Strangely, the time left is correct on the disc, but it shows 0 tracks.

![image](https://user-images.githubusercontent.com/5914885/76623872-8c9c9c00-6534-11ea-9c9f-5b718eb350a9.png)

Edit: using an MZ-N710 and OSX 10.15

**Comment by astnmrtn** [comment]
Just wanted to add, that MP3 transfers (and I assume FLAC) are sent to the player (on my other Mac running 10.14) and appear to show TOC, so there's a read issue, perhaps?

**Comment by astnmrtn** [comment]
After a restart, tracks are sending from 10.15 as well. However, not all mp3s are visible for some reason.

**Comment by gavinbenda** [comment]
That is pretty odd! Are they within a 'Group' by any chance?

**Comment by gavinbenda** [comment]
This is prob the same as #12

**Comment by ticky** [comment]
I think I found the issue - if the binary included in this project is the same as one built from your fork of linux-minidisc, [this change](https://github.com/gavinbenda/linux-minidisc/commit/185bc72b9d7c3bca65e4ddc2b696fe434243800a#diff-29214a8a32e39506120409a869688cf9L597-R613) skips printing JSON data for any tracks with an empty title. The original if statement condition was checking for less-than-zero return codes, which would indicate an error retrieving the information.

**Comment by gavinbenda** [comment]
Wow fantastic pick up!

**Comment by gavinbenda** [comment]
Have just pushed a new release out, which should fix this issue amount other things.

**Comment by ticky** [comment]
Looking good from here!

It does seem like an issue remains where some text doesn’t parse as a valid JSON string, and therefore the whole list is blank; particularly noticeable on discs with Japanese text. I think integrating my libnetmd patch (glaubitz/linux-minidisc#56) would help avoid that by consistently providing UTF-8 text!
